// demo-angular/src/app/app.ts
import { Component } from '@angular/core';
import { getTop, closeAll } from 'css-drawer';

@Component({
  selector: 'app-root',
  imports: [],
  template: `
    <main class="demo">
      <h1>CSS Drawer - Angular</h1>
      <p>Using the vanilla JS API with Angular</p>

      <div class="demo-buttons">
        <button class="btn btn--primary" (click)="openDrawer(bottomDrawer)">
          Bottom Drawer
        </button>
        <button class="btn btn--secondary" (click)="openDrawer(modalDrawer)">
          Modal
        </button>
        <button class="btn btn--secondary" (click)="openDrawer(fullscreenModal)">
          Fullscreen Modal
        </button>
        <button class="btn btn--secondary" (click)="openDrawer(rightDrawer)">
          Right Drawer
        </button>
        <button class="btn btn--secondary" (click)="openDrawer(shareDialog)">
          Share (DOM Nested)
        </button>
        <button class="btn btn--secondary" (click)="openDrawer(settingsDrawer)">
          Nested (getTop)
        </button>
      </div>
    </main>

    <!-- Bottom Drawer -->
    <dialog #bottomDrawer class="drawer">
      <div class="drawer-handle"></div>
      <div class="drawer-content">
        <h2>Bottom Drawer</h2>
        <p>This drawer opens from the bottom (default direction).</p>
        <button class="btn btn--secondary btn--full" (click)="closeDrawer(bottomDrawer)">
          Close
        </button>
      </div>
    </dialog>

    <!-- Modal -->
    <dialog #modalDrawer class="drawer" data-direction="modal">
      <div class="drawer-content">
        <h2>Centered Modal</h2>
        <p>Uses direction="modal" to open as a centered dialog with scale animation.</p>
        <div class="actions">
          <button class="btn btn--primary btn--full" (click)="openDrawer(nestedModal)">
            Open Nested Modal
          </button>
          <button class="btn btn--secondary btn--full" (click)="closeDrawer(modalDrawer)">
            Close
          </button>
        </div>
      </div>
    </dialog>

    <!-- Nested Modal (sibling) -->
    <dialog #nestedModal class="drawer" data-direction="modal">
      <div class="drawer-content">
        <h2>Nested Modal</h2>
        <p>Modals can stack just like drawers.</p>
        <button class="btn btn--primary btn--full" (click)="closeDrawer(nestedModal)">
          Close
        </button>
      </div>
    </dialog>

    <!-- Fullscreen Modal -->
    <dialog #fullscreenModal class="drawer" data-direction="modal" style="--drawer-modal-width: 90%; --drawer-modal-height: 90%;">
      <div class="drawer-content" style="text-align: center; padding-top: 2rem;">
        <h2>Fullscreen Modal</h2>
        <p>Uses --drawer-modal-width: 100% and --drawer-modal-height: 100% for fullscreen.</p>
        <button class="btn btn--primary btn--full" (click)="closeDrawer(fullscreenModal)">
          Close
        </button>
      </div>
    </dialog>

    <!-- DOM-Nested Test: Child dialog inside parent dialog -->
    <dialog #shareDialog class="drawer" data-direction="modal" (close)="onShareClose()">
      <div class="drawer-content">
        <h2>Share</h2>
        <p>Share this item with others.</p>
        <div style="display: flex; align-items: center; gap: 0.5rem; padding: 0.75rem; background: #f5f5f5; border-radius: 8px; margin-bottom: 1rem;">
          <input type="text" readonly value="https://example.com/share/abc123" style="flex: 1; border: none; background: transparent; font-size: 0.875rem; color: #666;" />
          <button class="btn btn--primary" style="padding: 0.5rem 1rem;" (click)="openDrawer(copyConfirmDialog)">
            Copy
          </button>
        </div>
        <button class="btn btn--secondary btn--full" (click)="closeDrawer(shareDialog)">
          Done
        </button>

        <!-- Child dialog - DOM nested inside parent -->
        <dialog #copyConfirmDialog class="drawer" data-direction="modal" (close)="onCopyConfirmClose()">
          <div class="drawer-content" style="text-align: center;">
            <div style="width: 48px; height: 48px; margin: 0 auto 1rem; display: grid; place-items: center; border-radius: 50%; background: rgba(34, 197, 94, 0.1); color: rgb(34, 197, 94);">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </div>
            <h2>Link Copied!</h2>
            <p>The share link has been copied to your clipboard.</p>
            <button class="btn btn--primary btn--full" (click)="closeDrawer(copyConfirmDialog)">
              OK
            </button>
          </div>
        </dialog>
      </div>
    </dialog>

    <!-- Right Drawer -->
    <dialog #rightDrawer class="drawer" data-direction="right">
      <div class="drawer-content">
        <h2>Right Drawer</h2>
        <p>This drawer opens from the right.</p>
        <button class="btn btn--secondary btn--full" (click)="closeDrawer(rightDrawer)">
          Close
        </button>
      </div>
    </dialog>

    <!-- Settings Drawer (demonstrates subscribe API) -->
    <dialog #settingsDrawer class="drawer" data-direction="bottom">
      @if (isTopDrawer(settingsDrawer)) {
        <div class="top-badge">Top Drawer</div>
      }
      <div class="drawer-content">
        <h2>Settings</h2>
        <p>Nested drawers using getTop(). Notice the badge only shows on the topmost drawer.</p>
        <div class="actions">
          <button class="btn btn--secondary btn--full" style="color: #dc2626;" (click)="openDrawer(deleteConfirmDrawer)">
            Delete Account
          </button>
          <button class="btn btn--secondary btn--full" (click)="closeDrawer(settingsDrawer)">
            Close
          </button>
        </div>
      </div>
    </dialog>

    <!-- Delete Confirm Drawer -->
    <dialog #deleteConfirmDrawer class="drawer" data-direction="bottom">
      @if (isTopDrawer(deleteConfirmDrawer)) {
        <div class="top-badge">Top Drawer</div>
      }
      <div class="drawer-content" style="text-align: center;">
        <h2>Are you sure?</h2>
        <p>This action cannot be undone.</p>
        <div class="actions">
          <button class="btn btn--full" style="background: #dc2626; color: white;" (click)="closeAllDrawers()">
            Yes, Delete
          </button>
          <button class="btn btn--secondary btn--full" (click)="closeDrawer(deleteConfirmDrawer)">
            Cancel
          </button>
        </div>
      </div>
    </dialog>
  `,
  styles: [`
    .demo {
      min-height: 100dvh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 2rem;
      text-align: center;
    }

    h1 {
      font-size: 2rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    p {
      color: #666;
      margin-bottom: 2rem;
    }

    .demo-buttons {
      display: flex;
      gap: 0.75rem;
      flex-wrap: wrap;
      justify-content: center;
    }

    .btn {
      padding: 0.75rem 1.5rem;
      border-radius: 8px;
      font-weight: 500;
      cursor: pointer;
      border: none;
      transition: all 0.15s ease;
    }

    .btn--primary {
      background: #0066ff;
      color: white;
    }

    .btn--primary:hover {
      background: #0052cc;
    }

    .btn--secondary {
      background: #f0f0f0;
      color: #333;
    }

    .btn--secondary:hover {
      background: #e0e0e0;
    }

    .btn--full {
      width: 100%;
    }

    .drawer-content {
      padding: 1.5rem;
    }

    .drawer-content h2 {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 0.5rem;
    }

    .drawer-content p {
      color: #666;
      margin-bottom: 1.5rem;
    }

    .actions {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .top-badge {
      position: absolute;
      top: 0.75rem;
      right: 0.75rem;
      padding: 0.25rem 0.5rem;
      background: hsl(200 98% 39%);
      color: white;
      font-size: 0.75rem;
      font-weight: 500;
      border-radius: 4px;
    }
  `],
})
export class App {
  openDrawer(dialog: HTMLDialogElement) {
    dialog.showModal();
  }

  closeDrawer(dialog: HTMLDialogElement) {
    dialog.close();
  }

  closeAllDrawers() {
    closeAll();
  }

  isTopDrawer(dialog: HTMLDialogElement): boolean {
    return getTop() === dialog;
  }

  onShareClose() {
    console.log('[SHARE/PARENT] close event fired');
  }

  onCopyConfirmClose() {
    console.log('[COPY CONFIRM/CHILD] close event fired');
  }
}

// demo/src/App.tsx
import { useRef, useState, type RefObject } from 'react'
import { Drawer, useIsTopDrawer } from 'css-drawer/react'
import { useIsMobile } from './hooks/useMediaQuery'

/** Demo component showing useIsTopDrawer hook */
function TopDrawerBadge({ drawerRef }: { drawerRef: RefObject<HTMLDialogElement | null> }) {
  const isTop = useIsTopDrawer(drawerRef)

  if (!isTop) return null

  return (
    <div style={{
      position: 'absolute',
      top: '0.75rem',
      right: '0.75rem',
      padding: '0.25rem 0.5rem',
      background: 'hsl(200 98% 39%)',
      color: 'white',
      fontSize: '0.75rem',
      fontWeight: 500,
      borderRadius: '4px',
    }}>
      Top Drawer
    </div>
  )
}

export default function App() {
  const formRef = useRef<HTMLDialogElement>(null)
  const confirmRef = useRef<HTMLDialogElement>(null)
  const successRef = useRef<HTMLDialogElement>(null)
  const bottomRef = useRef<HTMLDialogElement>(null)
  const modalRef = useRef<HTMLDialogElement>(null)
  const nestedModalRef = useRef<HTMLDialogElement>(null)
  const fullscreenModalRef = useRef<HTMLDialogElement>(null)

  // Controlled mode example
  const [rightOpen, setRightOpen] = useState(false)

  // Nested controlled mode example
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false)
  const settingsRef = useRef<HTMLDialogElement>(null)
  const deleteConfirmRef = useRef<HTMLDialogElement>(null)

  // DOM-nested dialogs (child rendered inside parent)
  const [shareOpen, setShareOpen] = useState(false)
  const [copyConfirmOpen, setCopyConfirmOpen] = useState(false)

  const isMobile = useIsMobile(768)
  const responsiveDirection = isMobile ? undefined : 'right'

  function handleConfirm() {
    confirmRef.current?.close()
    formRef.current?.close()
    successRef.current?.showModal()
  }

  return (
    <>
      <main className="demo">
        <h1>CSS Drawer</h1>
        <p>Zero React state. Native dialog refs only. Try nested drawers.</p>
        <div className="demo-buttons">
          <button
            className="btn btn--primary"
            onClick={() => formRef.current?.showModal()}
          >
            Open Form
          </button>

          <button
            className="btn btn--secondary"
            onClick={() => bottomRef.current?.showModal()}
          >
            Bottom Drawer
          </button>

          <button
            className="btn btn--secondary"
            onClick={() => modalRef.current?.showModal()}
          >
            Modal
          </button>

          <button
            className="btn btn--secondary"
            onClick={() => fullscreenModalRef.current?.showModal()}
          >
            Fullscreen Modal
          </button>

          <button
            className="btn btn--secondary"
            onClick={() => setRightOpen(true)}
          >
            Right Drawer (Controlled)
          </button>

          <button
            className="btn btn--secondary"
            onClick={() => setSettingsOpen(true)}
          >
            Nested (Controlled)
          </button>

          <button
            className="btn btn--secondary"
            onClick={() => setShareOpen(true)}
          >
            Share (DOM Nested)
          </button>
        </div>
      </main>

      {/* Form Drawer - direction is responsive */}
      <Drawer.Root direction={responsiveDirection}>
        <Drawer.Content ref={formRef} closeOnOutsideClick={false}>
          {isMobile && <Drawer.Handle />}
          <div className="drawer-content">
            <Drawer.Title>Create Issue</Drawer.Title>
            <Drawer.Description>
              Fill out the form. Opens from right on desktop, bottom on mobile.
            </Drawer.Description>
            <form onSubmit={(e) => {
              e.preventDefault()
              confirmRef.current?.showModal()
            }}>
              <div className="form-group">
                <label htmlFor="title">Title</label>
                <input type="text" id="title" placeholder="Issue title..." />
              </div>
              <div className="form-group">
                <label htmlFor="desc">Description</label>
                <textarea id="desc" placeholder="Describe the issue..." />
              </div>
              <div className="form-group">
                <label htmlFor="priority">Priority</label>
                <select id="priority">
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                  <option value="critical">Critical</option>
                </select>
              </div>
              <div className="form-group">
                <label htmlFor="assignee">Assignee</label>
                <input type="text" id="assignee" placeholder="Enter assignee name..." />
              </div>
              <div className="form-group">
                <label htmlFor="labels">Labels</label>
                <input type="text" id="labels" placeholder="bug, feature, docs..." />
              </div>
              <div className="form-group">
                <label htmlFor="due-date">Due Date</label>
                <input type="date" id="due-date" />
              </div>
              <div className="form-group">
                <label htmlFor="estimate">Time Estimate (hours)</label>
                <input type="number" id="estimate" placeholder="4" min="0" />
              </div>
              <div className="form-group">
                <label htmlFor="notes">Additional Notes</label>
                <textarea id="notes" placeholder="Any extra context..." />
              </div>
              <div className="actions">
                <button
                  type="button"
                  className="btn btn--secondary"
                  onClick={() => formRef.current?.close()}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn--primary" style={{ flex: 1 }}>
                  Submit
                </button>
              </div>
            </form>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Confirm Drawer - nested on top of form */}
      <Drawer.Root direction={responsiveDirection}>
        <Drawer.Content ref={confirmRef}>
          {isMobile && <Drawer.Handle />}
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
            <Drawer.Title>Confirm Submission?</Drawer.Title>
            <Drawer.Description>
              This will create a new issue in the system.
            </Drawer.Description>
            <div className="actions" style={{ flexDirection: 'column' }}>
              <button
                className="btn btn--primary btn--full"
                onClick={handleConfirm}
              >
                Yes, Create Issue
              </button>
              <button
                className="btn btn--secondary btn--full"
                onClick={() => confirmRef.current?.close()}
              >
                Go Back
              </button>
            </div>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Success Drawer */}
      <Drawer.Root direction={responsiveDirection}>
        <Drawer.Content ref={successRef}>
          {isMobile && <Drawer.Handle />}
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
            <div style={{
              width: 56,
              height: 56,
              margin: '0 auto 1rem',
              display: 'grid',
              placeItems: 'center',
              borderRadius: '50%',
              background: 'hsl(142 71% 45% / 0.1)',
              color: 'hsl(142 71% 45%)'
            }}>
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </div>
            <Drawer.Title>Issue Created!</Drawer.Title>
            <Drawer.Description>
              Your issue has been submitted successfully.
            </Drawer.Description>
            <button
              className="btn btn--primary btn--full"
              style={{ marginTop: '1rem' }}
              onClick={() => successRef.current?.close()}
            >
              Done
            </button>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Simple Bottom Drawer */}
      <Drawer.Root>
        <Drawer.Content ref={bottomRef}>
          <Drawer.Handle />
          <div className="drawer-content">
            <Drawer.Title>Simple Drawer</Drawer.Title>
            <Drawer.Description>
              This drawer opens from the bottom (default direction).
            </Drawer.Description>
            <button
              className="btn btn--secondary btn--full"
              onClick={() => bottomRef.current?.close()}
            >
              Close
            </button>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Modal */}
      <Drawer.Root direction="modal">
        <Drawer.Content ref={modalRef}>
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
            <Drawer.Title>Centered Modal</Drawer.Title>
            <Drawer.Description>
              Uses direction="modal" to open as a centered dialog with scale animation.
            </Drawer.Description>
            <div className="actions" style={{ flexDirection: 'column' }}>
              <button
                className="btn btn--primary btn--full"
                onClick={() => nestedModalRef.current?.showModal()}
              >
                Open Nested Modal
              </button>
              <button
                className="btn btn--secondary btn--full"
                onClick={() => modalRef.current?.close()}
              >
                Close
              </button>
            </div>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Nested Modal */}
      <Drawer.Root direction="modal">
        <Drawer.Content ref={nestedModalRef}>
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
            <Drawer.Title>Nested Modal</Drawer.Title>
            <Drawer.Description>
              Modals can stack just like drawers.
            </Drawer.Description>
            <button
              className="btn btn--primary btn--full"
              onClick={() => nestedModalRef.current?.close()}
            >
              Close
            </button>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Fullscreen Modal */}
      <Drawer.Root direction="modal">
        <Drawer.Content
          ref={fullscreenModalRef}
          style={{
            '--drawer-modal-width': '90%',
            '--drawer-modal-height': '90%',
          } as React.CSSProperties}
        >
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '2rem' }}>
            <Drawer.Title>Fullscreen Modal</Drawer.Title>
            <Drawer.Description>
              Uses --drawer-width: 100% and --drawer-height: 100% for fullscreen.
            </Drawer.Description>
            <button
              className="btn btn--primary btn--full"
              onClick={() => fullscreenModalRef.current?.close()}
            >
              Close
            </button>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Right Drawer - Controlled Mode */}
      <Drawer.Root direction="right">
        <Drawer.Content open={rightOpen} onOpenChange={setRightOpen}>
          <div className="drawer-content">
            <Drawer.Title>Right Drawer (Controlled)</Drawer.Title>
            <Drawer.Description>
              Uses React state instead of refs. Open: {rightOpen ? 'true' : 'false'}
            </Drawer.Description>
            <button
              className="btn btn--secondary btn--full"
              onClick={() => setRightOpen(false)}
            >
              Close
            </button>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* Nested Drawers - Controlled Mode with useIsTopDrawer demo */}
      <Drawer.Root direction={responsiveDirection}>
        <Drawer.Content ref={settingsRef} open={settingsOpen} onOpenChange={setSettingsOpen}>
          {isMobile && <Drawer.Handle />}
          <TopDrawerBadge drawerRef={settingsRef} />
          <div className="drawer-content">
            <Drawer.Title>Settings</Drawer.Title>
            <Drawer.Description>
              Nested drawers using controlled mode. Notice the badge only shows on the topmost drawer.
            </Drawer.Description>
            <div className="actions" style={{ flexDirection: 'column' }}>
              <button
                className="btn btn--secondary btn--full"
                onClick={() => setDeleteConfirmOpen(true)}
                style={{ color: 'hsl(0 84% 60%)' }}
              >
                Delete Account
              </button>
              <button
                className="btn btn--secondary btn--full"
                onClick={() => setSettingsOpen(false)}
              >
                Close
              </button>
            </div>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      <Drawer.Root direction={responsiveDirection}>
        <Drawer.Content ref={deleteConfirmRef} open={deleteConfirmOpen} onOpenChange={setDeleteConfirmOpen}>
          {isMobile && <Drawer.Handle />}
          <TopDrawerBadge drawerRef={deleteConfirmRef} />
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
            <Drawer.Title>Are you sure?</Drawer.Title>
            <Drawer.Description>
              This action cannot be undone.
            </Drawer.Description>
            <div className="actions" style={{ flexDirection: 'column' }}>
              <button
                className="btn btn--full"
                style={{ background: 'hsl(0 84% 60%)', color: 'white' }}
                onClick={() => {
                  setDeleteConfirmOpen(false)
                  setSettingsOpen(false)
                }}
              >
                Yes, Delete
              </button>
              <button
                className="btn btn--secondary btn--full"
                onClick={() => setDeleteConfirmOpen(false)}
              >
                Cancel
              </button>
            </div>
          </div>
        </Drawer.Content>
      </Drawer.Root>

      {/* DOM-Nested: Child dialog rendered inside parent dialog */}
      <Drawer.Root direction="modal">
        <Drawer.Content open={shareOpen} onOpenChange={setShareOpen}>
          <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
            <Drawer.Title>Share</Drawer.Title>
            <Drawer.Description>
              Share this item with others.
            </Drawer.Description>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              padding: '0.75rem',
              background: 'hsl(0 0% 95%)',
              borderRadius: '8px',
              marginBottom: '1rem'
            }}>
              <input
                type="text"
                readOnly
                value="https://example.com/share/abc123"
                style={{
                  flex: 1,
                  border: 'none',
                  background: 'transparent',
                  fontSize: '0.875rem',
                  color: 'hsl(0 0% 40%)'
                }}
              />
              <button
                className="btn btn--primary"
                style={{ padding: '0.5rem 1rem' }}
                onClick={() => setCopyConfirmOpen(true)}
              >
                Copy
              </button>
            </div>
            <button
              className="btn btn--secondary btn--full"
              onClick={() => setShareOpen(false)}
            >
              Done
            </button>

            {/* Confirmation toast - DOM nested inside share dialog */}
            <Drawer.Root direction="modal">
              <Drawer.Content open={copyConfirmOpen} onOpenChange={setCopyConfirmOpen}>
                <div className="drawer-content" style={{ textAlign: 'center', paddingTop: '1rem' }}>
                  <div style={{
                    width: 48,
                    height: 48,
                    margin: '0 auto 1rem',
                    display: 'grid',
                    placeItems: 'center',
                    borderRadius: '50%',
                    background: 'hsl(142 71% 45% / 0.1)',
                    color: 'hsl(142 71% 45%)'
                  }}>
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  </div>
                  <Drawer.Title>Link Copied!</Drawer.Title>
                  <Drawer.Description>
                    The share link has been copied to your clipboard.
                  </Drawer.Description>
                  <button
                    className="btn btn--primary btn--full"
                    onClick={() => setCopyConfirmOpen(false)}
                  >
                    OK
                  </button>
                </div>
              </Drawer.Content>
            </Drawer.Root>
          </div>
        </Drawer.Content>
      </Drawer.Root>
    </>
  )
}
